import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { AppHeader, BottomNav } from "../components/app-nav";
import { ProjectProgress } from "../components/project-progress";

function prettyLevel(level?:string|null){if(!level)return"Peach Creative";return`Peach ${level[0].toUpperCase()+level.slice(1)}`}

export default async function CreativeDashboard(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth?role=creative&mode=signin");const admin=createAdminClient();
 const{data:profile}=await admin.from("profiles").select("full_name,role,avatar_url").eq("id",user.id).single();if(profile?.role==="business")redirect("/business");if(profile?.role==="admin")redirect("/admin");
 const{data:creative}=await admin.from("creatives").select("id,peach_level,application_status,primary_specialty,city,state,reliability_score,profile_image_url").eq("user_id",user.id).single();if(!creative)redirect("/creative/apply");if(creative.application_status!=="approved")redirect("/creative/status");
 const[{data:offers},{data:payouts},{data:projects}]=await Promise.all([admin.from("project_offers").select("id,payout_cents,expires_at,project_id,status,projects(title,category,due_at,revision_rounds)").eq("creative_id",creative.id).in("status",["sent","countered"]).order("created_at",{ascending:false}).limit(4),admin.from("creative_payouts").select("amount_cents,status").eq("creative_id",creative.id).in("status",["pending","ready","approved"]),admin.from("projects").select("id,title,category,status,coin_amount,due_at,created_at").eq("assigned_creative_id",creative.id).order("created_at",{ascending:false}).limit(4)]);
 const pending=(payouts??[]).reduce((s:number,p:any)=>s+(p.amount_cents??0),0);const active=(projects??[]).filter((p:any)=>!["completed","cancelled"].includes(p.status));const first=profile?.full_name?.split(" ")?.[0]??"Creative";
 return <main className="app-shell pn-app-shell"><AppHeader name={profile?.full_name} role="creative"/>
  <section className="pn-dashboard-hero"><div className="pn-dashboard-copy"><span className="eyebrow">CREATIVE HOME</span><h1>Hey, {first}. Your next opportunity could start here.</h1><p>Private Peach Matches, clear scope, visible payout and one workspace for the whole project.</p><Link href="/creative/offers" className="pn-find-card"><span className="pn-find-image"><img src={creative.profile_image_url||profile?.avatar_url||"/brand/hero-creative.jpg"} alt="Creative profile"/></span><div><small>PEACH MATCH</small><strong>See opportunities chosen for your profile.</strong></div><b>›</b></Link></div><div className="pn-dashboard-photo"><img src={creative.profile_image_url||profile?.avatar_url||"/brand/login-creative.jpg"} alt="Creative professional"/><div className="pn-photo-caption"><small>{prettyLevel(creative.peach_level).toUpperCase()}</small><strong>{creative.primary_specialty||"Creative professional"}</strong></div></div></section>
  <section className="pn-dashboard-stat-grid"><Link href="/creative/offers"><span>🍑</span><strong>{offers?.length??0}</strong><small>Matches</small><em>private opportunities</em></Link><Link href="/creative/projects"><span>▣</span><strong>{active.length}</strong><small>Projects</small><em>active work</em></Link><Link href="/creative/payouts"><span>$</span><strong>${(pending/100).toFixed(0)}</strong><small>Payout</small><em>pending</em></Link><Link href="/network"><span>✦</span><strong>Events</strong><small>Network</small><em>learn + connect</em></Link></section>
  <section className="pn-ai-home-card"><div className="pn-ai-orb">🍑</div><div><span className="eyebrow">PEACH MATCH</span><h2>A shortlist, not a pile.</h2><p>Peach sends opportunities that fit your specialty, level, portfolio and availability. You see the scope, payout and deadline before you decide.</p><Link href="/creative/offers" className="text-link">Review matches →</Link></div></section>
  <div className="section-row pn-section-row"><div><span className="eyebrow">OPPORTUNITIES</span><h2>Matched for you.</h2></div><Link href="/creative/offers" className="text-link">View all</Link></div>
  <section className="pn-project-card-list">{(offers??[]).slice(0,2).map((o:any)=><article className="pn-project-card-new" key={o.id}><div className="pn-card-person"><img src="/brand/business-owner.jpg" alt="Business client"/></div><div className="pn-card-project-main"><div className="pn-project-topline"><div><small>PRIVATE MATCH</small><h3>{o.projects?.title??"Creative Opportunity"}</h3></div><strong>${(o.payout_cents/100).toFixed(0)}</strong></div><p>{o.projects?.category??"Creative"}{o.projects?.due_at?` · Due ${new Date(o.projects.due_at).toLocaleDateString()}`:""}</p><div className="pn-card-project-bottom"><span>Scope + payout visible before you accept.</span><Link href="/creative/offers" className="btn btn-primary btn-small">Review Match</Link></div></div></article>)}{(!offers||offers.length===0)&&<div className="pn-friendly-empty"><span>🍑</span><div><h3>Nothing ripe yet.</h3><p>Peach is looking. Your next private match will appear here when the fit is right.</p></div></div>}</section>
  <div className="section-row pn-section-row"><div><span className="eyebrow">ACTIVE WORK</span><h2>Keep it moving.</h2></div><Link href="/creative/projects" className="text-link">View projects</Link></div>
  <section className="pn-project-card-list">{active.slice(0,2).map((p:any)=><article className="pn-project-card-new" key={p.id}><div className="pn-card-person"><img src="/brand/business-owner.jpg" alt="Business client"/></div><div className="pn-card-project-main"><div className="pn-project-topline"><div><small>{p.category}</small><h3>{p.title}</h3></div><span className={`status-label ${p.status}`}>{p.status.replaceAll("_"," ")}</span></div><p>{p.due_at?`Due ${new Date(p.due_at).toLocaleDateString()}`:"Flexible deadline"}</p><ProjectProgress status={p.status} compact/><div className="pn-card-project-bottom"><span>Chat, proofs and check-ins live together.</span><Link href={`/projects/${p.id}`} className="btn btn-primary btn-small">Open Workspace</Link></div></div></article>)}</section>
  <BottomNav role="creative" active="home"/>
 </main>
}
