"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Asset={id:string;label:string;kind:string;value:string|null;notes:string|null;original_name:string|null;storage_path:string|null;size_bytes:number};
const groups=[['logo','Logos & marks'],['color','Brand colors'],['font','Typefaces & fonts'],['photo','Photos & imagery'],['guide','Brand guides'],['other','Other assets']];
const blank={id:"",label:"",kind:"logo",value:"",notes:""};
export default function VaultManager({assets}:{assets:Asset[]}) {
  const router=useRouter();const [form,setForm]=useState(blank);const [editing,setEditing]=useState(false);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [removeId,setRemoveId]=useState<string|null>(null);
  function edit(asset?:Asset){setForm(asset?{id:asset.id,label:asset.label,kind:asset.kind,value:asset.value??"",notes:asset.notes??""}:blank);setFile(null);setEditing(true);setMessage("")}
  async function json(url:string,method:string,body?:unknown){const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||"Please try again.");return data}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");try {
    if(file){
      if(file.size>25*1024*1024)throw Error("Choose a file 25 MB or smaller.");
      const upload=await json("/api/brand-vault","POST",{action:"upload",name:file.name});
      const {error}=await createClient().storage.from("brand-vault").uploadToSignedUrl(upload.path,upload.token,file,{contentType:file.type||"application/octet-stream"});
      if(error)throw Error(error.message);
      await json("/api/brand-vault","POST",{...form,path:upload.path});
    } else if(form.id)await json(`/api/brand-vault/${form.id}`,"PATCH",form);
    else await json("/api/brand-vault","POST",form);
    setEditing(false);setFile(null);setMessage("Asset saved. It is ready for your projects.");router.refresh();
  }catch(error){setMessage(error instanceof Error?error.message:"Could not save asset.")}finally{setBusy(false)}}
  async function remove(id:string){setBusy(true);try{await json(`/api/brand-vault/${id}`,"DELETE");setRemoveId(null);setMessage("Asset deleted.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Could not delete asset.")}finally{setBusy(false)}}
  return <div className="vault-manager"><div className="vault-toolbar"><span>{assets.length} saved {assets.length===1?"asset":"assets"}</span><button className="vault-primary" onClick={()=>edit()} disabled={busy}>+ Add brand asset</button></div>
    {message&&<p className="vault-notice" role="status">{message}</p>}
    {editing&&<form className="vault-editor" onSubmit={save}><h2>{form.id?"Edit brand asset":"Save a brand asset"}</h2><div className="vault-fields"><label>Asset name<input required maxLength={120} value={form.label} onChange={e=>setForm({...form,label:e.target.value})} placeholder="Primary logo, warm peach, heading font…"/></label><label>Category<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{groups.map(([kind,title])=><option key={kind} value={kind}>{title}</option>)}</select></label></div><label>{form.kind==="color"?"HEX color":"Font name or reference (optional with a file)"}<input value={form.value} onChange={e=>setForm({...form,value:e.target.value})} placeholder={form.kind==="color"?"#E85D3F":"Montserrat Bold, photography notes…"} required={form.kind==="color"}/></label><label>{form.id?"Replace file (optional)":"Upload file (optional for colors or font names)"}<input key={form.id||"new"} type="file" accept=".png,.jpg,.jpeg,.webp,.svg,.pdf,.ai,.eps,.zip,.otf,.ttf,.woff,.woff2,.ase,.txt,.docx" onChange={e=>setFile(e.target.files?.[0]??null)}/><small>Logos, photos, PDFs, font files and ZIPs · up to 25 MB</small></label><label>Usage notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Use on light backgrounds. Headlines only. Keep the clear space…" maxLength={2000}/></label><div className="vault-buttons"><button className="vault-primary" disabled={busy}>{busy?"Saving…":"Save asset"}</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></form>}
    <div className="vault-groups">{groups.map(([kind,title])=>{const items=assets.filter(a=>a.kind===kind);return <details key={kind} id={kind} className="vault-group" open={items.length>0}><summary><strong>{title}</strong><span>{items.length} <span aria-hidden="true">⌄</span></span></summary><div className="vault-group-body">{items.length?items.map(asset=><article key={asset.id} className="vault-asset"><span className="vault-asset-icon" style={asset.kind==="color"?{background:asset.value??"#eee"}:undefined} aria-hidden="true">{asset.kind!=="color"&&(asset.original_name?.split('.').pop()?.toUpperCase()||"Aa")}</span><div className="vault-asset-copy"><strong>{asset.label}</strong><span>{asset.value||asset.original_name}</span>{asset.notes&&<p>{asset.notes}</p>}</div><div className="vault-asset-actions">{asset.storage_path&&<a href={`/api/brand-vault/${asset.id}`}>Download</a>}<button onClick={()=>edit(asset)} disabled={busy}>Edit</button>{removeId===asset.id?<><button className="vault-delete" onClick={()=>remove(asset.id)} disabled={busy}>Confirm delete</button><button onClick={()=>setRemoveId(null)}>Keep</button></>:<button className="vault-delete" onClick={()=>setRemoveId(asset.id)} disabled={busy}>Delete</button>}</div></article>):<p className="vault-empty">No {title.toLowerCase()} saved yet. Add the files and details your creative should use every time.</p>}</div></details>})}</div>
    <style>{`.vault-manager{color:#263e33}.vault-toolbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;font-size:13px;color:#6a786f}.vault-manager button,.vault-manager a{font:inherit;cursor:pointer}.vault-primary{border:0!important;background:#e85d3f!important;color:white!important;border-radius:12px;padding:11px 16px!important;font-weight:750!important}.vault-manager button:disabled{opacity:.6;cursor:wait}.vault-notice{background:#edf4fa;padding:14px;border-radius:12px;font-size:13px}.vault-editor{padding:22px;border:1px solid #edc7b3;background:#fff8f4;border-radius:18px;margin-bottom:22px}.vault-editor h2{font-size:20px;margin:0 0 18px}.vault-fields{display:grid;grid-template-columns:1fr 1fr;gap:16px}.vault-editor label{display:grid;gap:7px;font-size:12px;font-weight:750;margin-bottom:16px}.vault-editor input,.vault-editor select,.vault-editor textarea{padding:11px;border:1px solid #ded7cf;border-radius:10px;background:white;font:inherit;min-width:0;width:100%;font-weight:400}.vault-editor small{color:#69776f;font-weight:400}.vault-buttons{display:flex;gap:10px}.vault-buttons button{border:1px solid #ddd5cd;background:white;border-radius:12px;padding:10px 16px}.vault-groups{display:grid;gap:14px}.vault-group{background:white;border:1px solid #e7e1d9;border-radius:16px;overflow:hidden}.vault-group summary{cursor:pointer;display:flex;align-items:center;justify-content:space-between;padding:18px;list-style:none}.vault-group summary::-webkit-details-marker{display:none}.vault-group summary>span{color:#8c9b92;font-size:12px}.vault-group-body{padding:0 18px 14px}.vault-asset{display:flex;align-items:center;gap:14px;padding:15px 0;border-top:1px solid #eee7df}.vault-asset-icon{width:46px;height:46px;border-radius:10px;border:1px solid #e7e1d9;background:#edf4fa;display:grid;place-items:center;flex-shrink:0;font-size:10px;color:#44647a;font-weight:800}.vault-asset-copy{display:grid;gap:4px;flex:1;min-width:0;overflow-wrap:anywhere}.vault-asset-copy strong{font-size:14px}.vault-asset-copy span,.vault-asset-copy p{font-size:12px;color:#69776f;margin:0;line-height:1.5}.vault-asset-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.vault-asset-actions button{border:0;background:none;padding:4px;color:#526a5c;font-size:12px}.vault-asset-actions a{font-size:12px;color:#526a5c;text-decoration:none}.vault-asset-actions .vault-delete{color:#b64731}.vault-empty{color:#78867d;font-size:13px;line-height:1.6}.vault-manager :focus-visible{outline:3px solid #69a6cf;outline-offset:3px}@media(max-width:650px){.vault-fields{grid-template-columns:1fr}.vault-asset{flex-wrap:wrap}.vault-asset-actions{width:100%;padding-left:60px}.vault-toolbar{gap:12px}}`}</style>
  </div>;
}
