'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {briefSections,roomStage,roomStatus,type RoomFile,type VaultAsset} from '@/lib/project-room';
import styles from './business-project-room.module.css';
type Project={id:string;title:string;description:string|null;category:string;assigned_creative_id:string|null;status:string;coin_amount:number;due_at:string|null;revision_rounds:number;current_revision_round:number|null};
type Props={proofThumbnail?:string|null;project:Project;creative:{name:string;avatar:string|null;specialty:string|null}|null;businessName:string;files:RoomFile[];assets:VaultAsset[];messages:{id:string;message:string;sender:string;created_at:string}[];requests:{id:string;request_type:string;note:string}[];initialBrief:boolean};
type Panel='brief'|'proof'|'revision'|'chat'|'upload'|'approve'|null;
export default function BusinessProjectRoom({project:p,creative,businessName,files,assets,messages,requests,initialBrief,proofThumbnail}:Props){
 const router=useRouter(),dialog=useRef<HTMLDialogElement>(null),fileInput=useRef<HTMLInputElement>(null);const [panel,setPanel]=useState<Panel>(initialBrief?'brief':null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[message,setMessage]=useState(''),[revision,setRevision]=useState(''),[preview,setPreview]=useState<{url:string;mime:string}|null>(null);
 const brief=briefSections(p.description),stage=roomStage(p.status),proofs=files.filter(f=>f.file_kind==='proof'),latest=proofs[0],finals=files.filter(f=>f.file_kind==='final'),unlocked=['approved','completed'].includes(p.status),canApprove=['proof_uploaded','submitted'].includes(p.status),canRevise=['proof_uploaded','submitted'].includes(p.status)&&(p.current_revision_round??0)<p.revision_rounds,closed=['completed','cancelled'].includes(p.status);
 useEffect(()=>{const el=dialog.current;if(!el)return;if(panel&&!el.open)el.showModal();if(!panel&&el.open)el.close();},[panel]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!panel&&!busy)router.refresh()},30000);return()=>clearInterval(timer)},[router,panel,busy]);
 async function post(url:string,body:unknown){setBusy(true);setNotice('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');setPanel(null);setMessage('');setRevision('');setNotice(d.vaultSynced===false?'Approval saved. Your files are unlocked; use Save to Brand Vault below to retry saving them.':'Saved. Your project is up to date.');router.refresh()}catch(e){setNotice(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 async function showProof(){setPreview(null);setPanel('proof');if(!latest)return;try{const r=await fetch(`/api/projects/files/${latest.id}/download?preview=1`);const d=await r.json();if(!r.ok)throw Error(d.error||'Could not open proof.');setPreview({url:d.url??'',mime:d.downloadOnly?'':latest.mime_type??''})}catch(e){setNotice(e instanceof Error?e.message:'Could not open proof.')}}
 async function upload(){const file=fileInput.current?.files?.[0];if(!file){setNotice('Choose a file first.');return}if(file.size>25*1024*1024){setNotice('Choose a file 25 MB or smaller.');return}setBusy(true);setNotice('');try{const prepare=await fetch('/api/projects/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:p.id,kind:'asset',action:'upload',name:file.name})}),signed=await prepare.json();if(!prepare.ok)throw Error(signed.error||'Upload failed.');const {error}=await createClient().storage.from('project-files').uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type||'application/octet-stream'});if(error)throw Error(error.message);const r=await fetch('/api/projects/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:p.id,kind:'asset',path:signed.path,name:file.name})}),d=await r.json();if(!r.ok)throw Error(d.error||'Upload failed.');setPanel(null);setNotice('File added to your project.');router.refresh()}catch(e){setNotice(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
 const open=(value:Panel)=>{setNotice('');setPanel(value)};
 const download=(f:RoomFile)=><a className={styles.file} key={f.id} href={`/api/projects/files/${f.id}/download`}><span><strong>{f.original_name}</strong><small>{f.note||f.file_kind.replaceAll('_',' ')}</small></span><b>Download</b></a>;
 const vaultRows=assets.map(a=><div className={styles.file} key={a.id}><span><strong>{a.label}</strong><small>{a.value||a.original_name} · Brand Vault{a.notes?` · ${a.notes}`:''}</small></span>{a.storage_path&&<a href={`/api/brand-vault/${a.id}?project=${p.id}`}>Download</a>}</div>);
 return <div className={styles.room}><header className={styles.header}><div><div className={styles.topline}><Link href="/business/projects">← Back to Projects</Link><span className={styles.badge}>{closed?'Project Room':'Active Project Room'}</span></div><h1>{p.title}</h1><div className={styles.metadata}><strong>{p.category} · {p.coin_amount} Peach Coins</strong>{creative&&<span>Assigned creative: {creative.name}</span>}<span className={styles.proofBadge}>{roomStatus(p.status)}</span><span>{p.due_at?`Due ${new Date(p.due_at).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/Chicago'})}`:'Flexible deadline'}</span></div></div>{latest&&<button className={styles.primary} onClick={showProof}>Review Proof</button>}</header>
 {notice&&<p className={styles.notice} role="status">{notice}</p>}
 {requests.length>0&&<section className={styles.request}><strong>Your creative needs something from you.</strong>{requests.map(r=><div key={r.id}><p>{r.request_type.replaceAll('_',' ')}: {r.note}</p><button disabled={busy} onClick={()=>post('/api/projects/client-request/resolve',{projectId:p.id,requestId:r.id})}>Mark sent</button></div>)}</section>}
 <div className={styles.grid}>
 <section className={`${styles.card} ${styles.brief}`}><div className={styles.cardHead}><span className={styles.badge}>Project Brief</span><button className={styles.textButton} onClick={()=>open('brief')}>Open Drawer →</button></div><h2>{p.title}</h2><p className={styles.clamp}>{brief.objective}</p><div className={styles.inset}><p><strong>Deliverables:</strong> {brief.format||'See the agreed project brief'}</p><p><strong>Vibe / Style:</strong> {brief.style||'See brand assets and brief'}</p><p><strong>Revisions:</strong> {p.revision_rounds} included rounds</p></div><button onClick={()=>open('brief')}>View Full Brief & Specs →</button></section>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.proofBadge}>Proofs & Revisions</span><small>{p.current_revision_round??0} of {p.revision_rounds} revisions used</small></div><div className={styles.proofArea}><div className={styles.proofThumb}>{latest?<>{proofThumbnail&&latest.mime_type?.startsWith('image/')?<img className={styles.thumbImage} src={proofThumbnail} alt="Latest project proof"/>:<span>{latest.original_name.split('.').pop()?.toUpperCase()}</span>}<strong>{latest.original_name}</strong><small>Creative proof</small></>:<><span>↗</span><strong>Your proof will appear here</strong></>}</div><div><h2>{latest?'Your proof is ready':roomStatus(p.status)}</h2><p>{latest?`Uploaded ${new Date(latest.created_at).toLocaleDateString('en-US',{month:'short',day:'numeric'})}`:'Your creative will share the first proof when it is ready.'}</p><div className={styles.inset}><strong>{p.revision_rounds} revision rounds included</strong><p>Review your proof and leave clear feedback before approval.</p></div></div></div><div className={styles.buttons}><button className={styles.primary} disabled={!latest} onClick={showProof}>Review Full Proof</button><button disabled={!canRevise} onClick={()=>open('revision')}>Request Revision</button></div></section>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.blueBadge}>Project Timeline</span><small>{closed?p.status==='completed'?'Complete':'Cancelled':`Stage ${stage+1} of 4`}</small></div><ol className={styles.timeline}>{['Brief & Creative Match','Work in Progress','Proof Review','Final Delivery'].map((title,i)=><li key={title} className={i===stage?styles.current:i<stage?styles.done:''}><span>{i<stage?'✓':i+1}</span><div><strong>{title}</strong><small>{i===stage?roomStatus(p.status):i<stage?'Complete':'Coming next'}</small></div></li>)}</ol><div className={styles.inset}>{p.due_at?`Delivery due ${new Date(p.due_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Chicago'})} CT`:'Delivery timing will be agreed with your creative.'}</div></section>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.badge}>Your Creative</span><small>Project partner</small></div><div className={styles.person}>{creative?.avatar?<img src={creative.avatar} alt={`${creative.name} profile`}/>:<span>{creative?.name.slice(0,1)||'P'}</span>}<div><h2>{creative?.name||'Finding your creative'}</h2><p>{creative?.specialty||'Your matched specialist will appear here.'}</p></div></div><div className={styles.inset}><p>Keep your questions, files and feedback together in this Project Room.</p><p>{assets.length} brand assets ready for this project.</p></div><button className={styles.dark} onClick={()=>open('chat')}>Message {creative?.name.split(' ')[0]||'your project team'}</button></section>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.neutralBadge}>Project Assets ({files.filter(f=>f.file_kind!=='final').length+assets.length})</span><small>Brand Vault connected</small></div><div className={styles.fileList}>{vaultRows.slice(0,2)}{files.filter(f=>f.file_kind!=='final').slice(0,2).map(download)}{!assets.length&&!files.length&&<p>No files yet. Add your references to get started.</p>}</div><button onClick={()=>open('upload')}>View Assets & Upload Files →</button></section>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.badge}>Project Messages</span><small>{messages.length} messages</small></div><div className={styles.messages}>{messages.slice(-2).map(m=><article key={m.id}><strong>{m.sender}</strong><p>{m.message}</p><small>{new Date(m.created_at).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></article>)}{!messages.length&&<p>No messages yet. Say hello to your project team.</p>}</div><button onClick={()=>open('chat')}>Open Conversation Thread →</button></section>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.greenBadge}>Payment Status</span><small>{p.status==='completed'?'Project completed':p.assigned_creative_id?'Coins committed':'Matching'}</small></div><h2>{p.coin_amount} Peach Coins</h2><p>{p.status==='completed'?'This project has been completed.':creative?'Coins were committed when your creative accepted.':'Coins are committed when your creative accepts.'}</p><div className={styles.protection}><strong>You review before sign-off.</strong><p>{p.status==='approved'?'Your approval is recorded. Peach handles the payout review.':'Review the work and approve it here when you are ready.'}</p></div><small>Creative payouts follow Peach’s approval process.</small></section>
 <section className={`${styles.card} ${styles.delivery}`}><div className={styles.cardHead}><span className={styles.neutralBadge}>Final Delivery & Brand Vault</span><small>{unlocked?'Available after approval':'Pending approval'}</small></div><h2>Final Files & Brand Vault Handoff</h2><p>{p.status==='approved'&&!finals.length?'Your proof is approved. Your creative can now prepare the final files.':unlocked?'Your approved files are ready to download and save for future projects.':'Review the proof first. Final source downloads unlock after final delivery approval.'}</p><div className={styles.finalList}>{finals.map(f=>unlocked?download(f):<div className={styles.file} key={f.id}><strong>{f.original_name}</strong><small>Pending approval</small></div>)}{!finals.length&&<div className={styles.inset}>Final deliverables will appear here when your creative uploads them.</div>}</div><div className={styles.buttons}>{canApprove&&<button className={styles.primary} onClick={()=>open('approve')}>{p.status==='submitted'?'Approve Final Delivery':'Approve Proof'}</button>}{unlocked&&finals.length>0&&<button disabled={busy} onClick={()=>post('/api/projects/vault-sync',{projectId:p.id})}>Save Final Files to Brand Vault</button>}<Link href="/business/vault">Open Brand Vault →</Link></div></section>
 </div>
 <dialog aria-label="Project details" ref={dialog} className={styles.dialog} onCancel={()=>setPanel(null)} onClick={e=>{if(e.target===dialog.current)setPanel(null)}}><div className={styles.drawer}><button className={styles.close} aria-label="Close drawer" onClick={()=>setPanel(null)}>✕</button><small className={styles.drawerLabel}>Project Room / {panel==='brief'?'Project Brief':panel}</small>
 {panel==='brief'&&<><h2>Project Brief & Creative Scope</h2><p>Agreed scope, deliverables and reference material.</p><h3>1. Project Objective & Narrative</h3><p className={styles.pre}>{brief.objective}</p><p>{p.coin_amount} Peach Coins · {p.revision_rounds} included revision rounds</p><h3>2. Exact Deliverables & Formats</h3><p className={styles.pre}>{brief.format||'Deliverables are described in the project objective above.'}</p>{brief.details&&<><h3>Content & Required Details</h3><p className={styles.pre}>{brief.details}</p></>}<h3>3. Creative Direction & Brand Rules</h3><p>{brief.style||'Use the business’s saved brand assets and agreed direction.'}</p><h3>4. Uploaded Assets & References ({assets.length+files.filter(f=>f.file_kind==='asset').length})</h3>{vaultRows}{files.filter(f=>f.file_kind==='asset').map(download)}</>}
 {panel==='proof'&&<><h2>Proof Review</h2>{latest?<><p>{latest.original_name}</p>{preview?preview.mime==='application/pdf'?<iframe sandbox="allow-same-origin" className={styles.preview} src={preview.url} title="Project proof preview"/>:['image/png','image/jpeg','image/webp'].includes(preview.mime)?<img className={styles.preview} src={preview.url} alt="Project proof"/>:<p>This format is available as a download.</p>:<p>Loading secure preview…</p>}{download(latest)}<div className={styles.buttons}>{canApprove&&<button className={styles.primary} onClick={()=>open('approve')}>{p.status==='submitted'?'Approve Final Delivery':'Approve Proof'}</button>}{canRevise&&<button onClick={()=>open('revision')}>Request Revision</button>}</div></>:<p>No proof has been uploaded yet.</p>}</>}
 {panel==='revision'&&<><h2>Request a Revision</h2><p>{p.revision_rounds-(p.current_revision_round??0)} included rounds remaining. Put all changes for this round into one message.</p><label>Your feedback<textarea value={revision} onChange={e=>setRevision(e.target.value)} placeholder="Tell your creative exactly what should change." maxLength={6000}/></label><button className={styles.primary} disabled={busy||!revision.trim()||!canRevise} onClick={()=>post('/api/projects/revisions',{projectId:p.id,requestText:revision.trim()})}>Send Revision Request</button></>}
 {panel==='chat'&&<><h2>Your Project Conversation</h2><p>{businessName} · {creative?.name||'Peach project team'}</p><div className={styles.thread}>{messages.map(m=><article key={m.id}><strong>{m.sender}</strong><p className={styles.pre}>{m.message}</p><small>{new Date(m.created_at).toLocaleString()}</small></article>)}</div><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write to your creative…" maxLength={6000}/></label><button className={styles.primary} disabled={busy||!message.trim()} onClick={()=>post('/api/projects/messages',{projectId:p.id,body:message.trim()})}>Send Message</button></>}
 {panel==='upload'&&<><h2>Project Assets & References</h2><p>Your saved Brand Vault assets are available to your assigned creative.</p>{vaultRows}{files.filter(f=>f.file_kind!=='final').map(download)}{!closed&&<><label>Upload an additional file<input ref={fileInput} type="file"/></label><small>Up to 25 MB per file.</small><button disabled={busy} className={styles.primary} onClick={upload}>{busy?'Uploading…':'Upload to Project'}</button></>}<Link href="/business/vault">Manage Brand Vault →</Link></>}
 {panel==='approve'&&<><h2>{p.status==='submitted'?'Approve Final Delivery?':'Approve This Proof?'}</h2><p>{p.status==='submitted'?'Confirm that the delivery meets your agreed brief. Approval unlocks the final downloads and saves them to your Brand Vault. Peach will review the creative payout.':'Confirm that this proof meets your brief. Your creative can then prepare the final delivery.'}</p><div className={styles.buttons}><button className={styles.primary} disabled={busy||!canApprove} onClick={()=>post('/api/projects/approve',{projectId:p.id})}>{busy?'Saving…':'Yes, Approve'}</button><button disabled={busy} onClick={()=>setPanel(null)}>Keep Reviewing</button></div></>}
 {notice&&<p role="status" className={styles.notice}>{notice}</p>}
 </div></dialog></div>
}
