"use client";
import { useState } from "react";
const services=[['Social Post','1 coin'],['Flyer / Event','1 coin'],['Simple Reel','2–3 coins'],['Website Update','2 coins'],['Logo Refresh','3–4 coins'],['Mini Photo Session','5–7 coins']];
export default function WalletActions(){
 const[tab,setTab]=useState<'membership'|'packs'>('membership');const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState('');const[ask,setAsk]=useState('');const[answer,setAnswer]=useState('');
 async function checkout(kind:'membership'|'pack',key:string){setBusy(`${kind}:${key}`);setMessage('');try{const r=await fetch('/api/stripe/create-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,key})});const text=await r.text();let body:any={};try{body=JSON.parse(text)}catch{throw new Error('Checkout is temporarily unavailable.')}if(!r.ok)throw new Error(body.error??'Could not start checkout.');window.location.href=body.url}catch(e){setMessage(e instanceof Error?e.message:'Could not start checkout.');setBusy(null)}}
 function estimate(){const q=ask.toLowerCase();let min=1,max=2;const bits:string[]=[];if(q.includes('flyer')){min+=1;max+=1;bits.push('flyer 1')}if(q.includes('reel')||q.includes('video')){min+=2;max+=4;bits.push('video 2–4')}if(q.includes('website')||q.includes('web')){min+=2;max+=5;bits.push('web 2–5')}if(q.includes('logo')){min+=3;max+=4;bits.push('logo 3–4')}if(q.includes('photo')){min+=5;max+=7;bits.push('photo 5–7')}if(!bits.length){min=1;max=3;bits.push('starting estimate 1–3')}setAnswer(`Peach estimate: about ${min}–${max} coins (${bits.join(', ')}). We’ll confirm the exact coin amount before work starts.`)}
 const plans=[['essentials','Essentials','5','499','For occasional creative help'],['growth','Growth','10','1,099','For businesses creating every month'],['partner','Partner','20','2,199','For bigger creative workloads']];
 const packs=[['pack3','3','425'],['pack5','5','675'],['pack10','10','1,250']];
 return <>
  <section className="v12-wallet-buy card"><div className="v12-tabs"><button className={tab==='membership'?'active':''} onClick={()=>setTab('membership')}>Monthly Membership</button><button className={tab==='packs'?'active':''} onClick={()=>setTab('packs')}>One-Time Peach Pack</button></div>
  {tab==='membership'?<div className="v12-plan-grid">{plans.map((p,i)=><article className={`v12-plan ${i===1?'featured':''}`} key={p[0]}>{i===1&&<span className="v12-popular">MOST POPULAR</span>}<h3>{p[1]}</h3><div><strong>{p[2]}</strong> <span>coins / month</span></div><b>${p[3]}<small>/month</small></b><p>{p[4]}</p><button className="btn btn-primary" disabled={!!busy} onClick={()=>checkout('membership',p[0])}>Choose {p[1]}</button></article>)}</div>:<div className="v12-plan-grid">{packs.map((p,i)=><article className={`v12-plan ${i===1?'featured':''}`} key={p[0]}>{i===1&&<span className="v12-popular">BEST STARTER</span>}<h3>{p[1]} Peach Coins</h3><b>${p[2]}</b><p>One-time creative credits. No membership required.</p><button className="btn btn-primary" disabled={!!busy} onClick={()=>checkout('pack',p[0])}>Buy {p[1]} Coins</button></article>)}</div>}</section>
  <section className="v12-coin-maker"><div className="section-row"><div><span className="eyebrow">WHAT CAN I MAKE?</span><h2>See what your coins can do.</h2></div></div><div className="v12-service-grid">{services.map(s=><div key={s[0]}><span className="v12-peach-mini">🍑</span><strong>{s[0]}</strong><small>{s[1]}</small></div>)}</div></section>
  <section className="v12-ask-peach pn-wallet-ai"><div className="v12-ai-mark">🍑</div><div className="v12-ai-copy"><span className="eyebrow">ASK PEACH AI · BETA</span><h2>Not sure how many coins you need?</h2><p>Describe the project. Peach gives you a quick planning estimate before you submit it for matching.</p><div className="v12-ai-compose"><input value={ask} onChange={e=>setAsk(e.target.value)} placeholder="I need a flyer and a 30-second promo video…"/><button onClick={estimate}>Ask Peach</button></div>{answer&&<div className="v12-ai-answer">{answer}</div>}<a className="text-link" href="/business/ask-peach">Open the full Peach assistant →</a></div></section>
  {message&&<div className="auth-message"><strong>Checkout needs attention.</strong> {message}</div>}
 </>
}
